apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-web
  name: test-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
      - image: 654654166929.dkr.ecr.ap-northeast-2.amazonaws.com/study-dockerimage-repo:28
        name: test-web
---
apiVersion: v1
kind: Service
metadata:
  name: test-web-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: test-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: test-web
